version: '3.7'
services:
  frontend:
    ports:
      - "8100:8100"
    image: "registry.heroku.com/whatsnear-frontend/web"
    hostname: frontend
    environment:
      PORT: 8100
      HOST_NAME: frontend
    env_file:
      - ../frontend/.env.docker.local


volumes:
  esdat1:
