version: '3.7'
services:
  backend:
    volumes:
      - ./backend/data:/app/data:rw,delegated
    ports:
      - '19000:19000'
    image: "registry.heroku.com/whatsnear-backend/web"
    hostname: backend
    environment:
      PORT: 19000
      SPRING_PROFILES_ACTIVE: "custom"
    env_file:
      - ../backend/.env.docker.local

volumes:
  esdat1:
