version: '3.7'
services:
  frontend:
    ports:
      - "8080:8080"
    image: "registry.heroku.com/whatsnear/web"
    hostname: frontend
    environment:
      HOST_NAME: frontend
      PORT: 8080
    env_file:
      - ../frontend/.env.docker.local


volumes:
  esdat1:
